name: git-actions-test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - name: Build the Docker imagee
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.REPO_NAME}}
    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.REPO_NAME}}
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - name: docker image pull
      run: docker pull ${{secrets.DOCKER_USER}}/${{secrets.REPO_NAME}}
    - name: docker run
      run: |
        docker ps -q --filter "name=hr_api" | grep -q . && docker stop hr_api && docker rm -fv hr_api
        docker run -d \
        --name hr_api \
        -e vault_url='${{secrets.VAULT_URL}}' \
        -e login_path='${{secrets.LOGIN_PATH}}' \
        -e cred_path='${{secrets.CRED_PATH}}' \
        -e project='${{secrets.PROJECT}}' \
        -e vault_password='${{secrets.VAULT_PASSWORD}}' \
        ${{secrets.DOCKER_USER}}/${{secrets.REPO_NAME}}
    - name: docker ps -a
      run: |
        docker ps -a
    - name: docker images
      run: |
        docker images
